version: "3.7"

services:
  nicotine:
    image: inalone/nicotine
    user: 1000:1000
    ports:
      - 8085:8085
    volumes:
      - /place/for/persistentdata:/home/nicotine
      - /place/for/incomplete:/home/nicotine/.local/share/nicotine/incomplete
      - /place/for/downloads:/home/nicotine/.local/share/nicotine/downloads
      - /place/for/uploads:/home/nicotine/.local/share/nicotine/received
    restart: unless-stopped
